# Generated by Django 4.1.3 on 2022-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("image", models.URLField(default=None)),
                ("release_date", models.DateField(default=None)),
                ("lte_exists", models.BooleanField(default=None)),
                ("slug", models.SlugField()),
            ],
        ),
    ]
